name: tests-ts

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn install
      - run: yarn test --coverage
